sudo: required
language: python
dist: xenial
python:
  - "3.7"
  - "3.6"

services:
  - docker

cache:
  - pip

before_install:
  - make start
  - docker ps -a

install:
  - make init

script:
  - make test

after_success:
   - codecov --token=f644f5f2-b455-4e5c-8ec6-fefce1fc587a

after_script:
  - make stop

notifications:
  email: false
